### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by TheLudd** [mllrsohn/angular-html2js#1]
Quoting the readme:

> Module is not yet on npm

Could this be changed? Right now I have added the dependency through github but this has the consequence that npm always checks for updates when I run `npm install`. This can be a bit bothersome if the connection is slow.

**Comment by steffenmllr** [comment]
To be honest, I'm using https://www.npmjs.org/package/gulp-angular-templatecache atm.
I only wrote this to get my head around stream ...

**Comment by TheLudd** [comment]
I see. Well I want to avoid all use of grunt/gulp and those tools and build my resources on the fly when receiving requests in my application instead of having a build step in my dev enviroment. Because of that I need to access call the methods that do the compilation myself. That is why I prefer this kind of project.

**Comment by steffenmllr** [comment]
Here you go: https://www.npmjs.org/package/angular-html2js

**Comment by TheLudd** [comment]
Very nice, thanks.
